default: &default
    adapter: postgresql
    encoding: unicode
    username: vramisetti
    username: postgres
    password: postvamsigres
    host: localhost
    # For details on connection pooling, see rails configuration guide
    # http://guides.rubyonrails.org/configuring.html#database-pooling
    pool: 5
production:
    <<: *default
    database: me_hubs_production


development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3
  pool: 5
